# Generated by Django 5.1.3 on 2024-11-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_status_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exerpt',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
