# Generated by Django 5.1.3 on 2024-11-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['approved', 'created']},
        ),
    ]
